# Generated by Django 5.2.7 on 2025-11-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidade',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='cidade',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='estado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='cidade',
            unique_together={('nome', 'estado', 'pais')},
        ),
        migrations.AlterModelTable(
            name='cidade',
            table='cidades',
        ),
    ]
